import type { Metadata } from "next";
import { Inter, Ubuntu } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Toaster from "@/components/Toaster";
import AuthProvider from "@/context/AuthProvider";
const inter = Inter({ subsets: ["latin"] });
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // Pass an array of weight values
});

export const metadata: Metadata = {
  title: "Learn Spoken English",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        {/* <body className={inter.className}> */}
        <body>
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
